launch_time_advance: 166.0 #seconds

periapsis: 200000.0 # m
apoapsis: 200000.0
altitude: 200000.0

inclination: 28.659 # deg
LAN: 0.0 # deg

direction: 'NORTH'

booster_burn_time: 123.0
first_stage_burn_time: 165.89 
